version: '3.8'
services:
  ghco:
    container_name: ghco-intraday-pnl
    init: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      awesome_network:
    stdin_open: true # docker run -i
    tty: true        # docker run -t

networks:
  awesome_network: